AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'bin/**'
    - 'node_modules/**/*'
  UseCache: true
  TargetRubyVersion: 2.5.1

Rails:
  Enabled: true

StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma